const elements = [
    { name: "Hydrogen", symbol: "H", number: 1, atomicMass: 1.008, category: "Nonmetal", info: "Lightest element, used in stars and water." },
    { name: "Helium", symbol: "He", number: 2, atomicMass: 4.0026, category: "Noble Gas", info: "Second most abundant element, used in balloons." },
    { name: "Lithium", symbol: "Li", number: 3, atomicMass: 6.94, category: "Alkali Metal", info: "Used in batteries and mood-stabilizing drugs." },
    { name: "Beryllium", symbol: "Be", number: 4, atomicMass: 9.0122, category: "Alkaline Earth Metal", info: "Lightweight metal used in aerospace materials." },
    { name: "Boron", symbol: "B", number: 5, atomicMass: 10.81, category: "Metalloid", info: "Important in borosilicate glass and detergents." },
    { name: "Carbon", symbol: "C", number: 6, atomicMass: 12.011, category: "Nonmetal", info: "Basis of all known life." },
    { name: "Nitrogen", symbol: "N", number: 7, atomicMass: 14.007, category: "Nonmetal", info: "Makes up 78% of Earth's atmosphere." },
    { name: "Oxygen", symbol: "O", number: 8, atomicMass: 15.999, category: "Nonmetal", info: "Essential for respiration and combustion." },
    { name: "Fluorine", symbol: "F", number: 9, atomicMass: 18.998, category: "Halogen", info: "Highly reactive, used in toothpaste." },
    { name: "Neon", symbol: "Ne", number: 10, atomicMass: 20.180, category: "Noble Gas", info: "Used in neon signs and high-voltage indicators." },
    { name: "Sodium", symbol: "Na", number: 11, atomicMass: 22.990, category: "Alkali Metal", info: "Common in salt and street lights." },
    { name: "Magnesium", symbol: "Mg", number: 12, atomicMass: 24.305, category: "Alkaline Earth Metal", info: "Important for biological systems." },
    { name: "Aluminum", symbol: "Al", number: 13, atomicMass: 26.982, category: "Post-Transition Metal", info: "Widely used lightweight metal." },
    { name: "Silicon", symbol: "Si", number: 14, atomicMass: 28.085, category: "Metalloid", info: "Main component of computer chips and sand." },
    { name: "Phosphorus", symbol: "P", number: 15, atomicMass: 30.974, category: "Nonmetal", info: "Essential for life, found in DNA." },
    { name: "Sulfur", symbol: "S", number: 16, atomicMass: 32.06, category: "Nonmetal", info: "Found in volcanic areas and proteins." },
    { name: "Chlorine", symbol: "Cl", number: 17, atomicMass: 35.45, category: "Halogen", info: "Used for water purification." },
    { name: "Argon", symbol: "Ar", number: 18, atomicMass: 39.948, category: "Noble Gas", info: "Used in welding and light bulbs." },
    { name: "Potassium", symbol: "K", number: 19, atomicMass: 39.098, category: "Alkali Metal", info: "Vital for biological functions." },
    { name: "Calcium", symbol: "Ca", number: 20, atomicMass: 40.078, category: "Alkaline Earth Metal", info: "Important for bones and teeth." },
    { name: "Scandium", symbol: "Sc", number: 21, atomicMass: 44.956, category: "Transition Metal", info: "Used in aerospace components." },
    { name: "Titanium", symbol: "Ti", number: 22, atomicMass: 47.867, category: "Transition Metal", info: "Strong and lightweight metal." },
    { name: "Vanadium", symbol: "V", number: 23, atomicMass: 50.942, category: "Transition Metal", info: "Used to make strong steel alloys." },
    { name: "Chromium", symbol: "Cr", number: 24, atomicMass: 51.996, category: "Transition Metal", info: "Known for its shiny, reflective surface." },
    { name: "Manganese", symbol: "Mn", number: 25, atomicMass: 54.938, category: "Transition Metal", info: "Important in steel production." },
    { name: "Iron", symbol: "Fe", number: 26, atomicMass: 55.845, category: "Transition Metal", info: "Crucial for blood (hemoglobin)." },
    { name: "Cobalt", symbol: "Co", number: 27, atomicMass: 58.933, category: "Transition Metal", info: "Used in magnets and batteries." },
    { name: "Nickel", symbol: "Ni", number: 28, atomicMass: 58.693, category: "Transition Metal", info: "Resistant to corrosion, used in coins." },
    { name: "Copper", symbol: "Cu", number: 29, atomicMass: 63.546, category: "Transition Metal", info: "Excellent conductor of electricity." },
    { name: "Zinc", symbol: "Zn", number: 30, atomicMass: 65.38, category: "Transition Metal", info: "Used for galvanization to prevent rust." }
  ];
  elements.push(
    { name: "Gallium", symbol: "Ga", number: 31, atomicMass: 69.723, category: "Post-Transition Metal", info: "Melts in your hand, used in semiconductors." },
    { name: "Germanium", symbol: "Ge", number: 32, atomicMass: 72.63, category: "Metalloid", info: "Used in fiber optics and infrared optics." },
    { name: "Arsenic", symbol: "As", number: 33, atomicMass: 74.922, category: "Metalloid", info: "A well-known poison and semiconductor material." },
    { name: "Selenium", symbol: "Se", number: 34, atomicMass: 78.971, category: "Nonmetal", info: "Used in photocopiers and glass production." },
    { name: "Bromine", symbol: "Br", number: 35, atomicMass: 79.904, category: "Halogen", info: "A red-brown liquid at room temperature." },
    { name: "Krypton", symbol: "Kr", number: 36, atomicMass: 83.798, category: "Noble Gas", info: "Used in lighting and photography." },
    { name: "Rubidium", symbol: "Rb", number: 37, atomicMass: 85.468, category: "Alkali Metal", info: "Highly reactive, used in research." },
    { name: "Strontium", symbol: "Sr", number: 38, atomicMass: 87.62, category: "Alkaline Earth Metal", info: "Used in fireworks for red color." },
    { name: "Yttrium", symbol: "Y", number: 39, atomicMass: 88.906, category: "Transition Metal", info: "Used in LEDs and superconductors." },
    { name: "Zirconium", symbol: "Zr", number: 40, atomicMass: 91.224, category: "Transition Metal", info: "Resistant to corrosion, used in nuclear reactors." },
    { name: "Niobium", symbol: "Nb", number: 41, atomicMass: 92.906, category: "Transition Metal", info: "Used in superconducting magnets." },
    { name: "Molybdenum", symbol: "Mo", number: 42, atomicMass: 95.95, category: "Transition Metal", info: "Essential for enzymes in living organisms." },
    { name: "Technetium", symbol: "Tc", number: 43, atomicMass: 98, category: "Transition Metal", info: "First artificially produced element." },
    { name: "Ruthenium", symbol: "Ru", number: 44, atomicMass: 101.07, category: "Transition Metal", info: "Used in electronics and jewelry." },
    { name: "Rhodium", symbol: "Rh", number: 45, atomicMass: 102.91, category: "Transition Metal", info: "Extremely reflective, used in mirrors and jewelry." },
    { name: "Palladium", symbol: "Pd", number: 46, atomicMass: 106.42, category: "Transition Metal", info: "Used in catalytic converters and jewelry." },
    { name: "Silver", symbol: "Ag", number: 47, atomicMass: 107.87, category: "Transition Metal", info: "Best electrical conductor among metals." },
    { name: "Cadmium", symbol: "Cd", number: 48, atomicMass: 112.41, category: "Transition Metal", info: "Used in batteries and pigments." },
    { name: "Indium", symbol: "In", number: 49, atomicMass: 114.82, category: "Post-Transition Metal", info: "Soft metal used in touchscreens." },
    { name: "Tin", symbol: "Sn", number: 50, atomicMass: 118.71, category: "Post-Transition Metal", info: "Used in solder and coatings for steel cans." },
    { name: "Antimony", symbol: "Sb", number: 51, atomicMass: 121.76, category: "Metalloid", info: "Used in flame retardants." },
    { name: "Tellurium", symbol: "Te", number: 52, atomicMass: 127.60, category: "Metalloid", info: "Used in solar panels and thermoelectric devices." },
    { name: "Iodine", symbol: "I", number: 53, atomicMass: 126.90, category: "Halogen", info: "Essential for thyroid health." },
    { name: "Xenon", symbol: "Xe", number: 54, atomicMass: 131.29, category: "Noble Gas", info: "Used in powerful lamps and anesthetics." },
    { name: "Cesium", symbol: "Cs", number: 55, atomicMass: 132.91, category: "Alkali Metal", info: "Highly reactive, used in atomic clocks." },
    { name: "Barium", symbol: "Ba", number: 56, atomicMass: 137.33, category: "Alkaline Earth Metal", info: "Used in medical imaging." },
    { name: "Lanthanum", symbol: "La", number: 57, atomicMass: 138.91, category: "Lanthanide", info: "Soft metal used in camera lenses." },
    { name: "Cerium", symbol: "Ce", number: 58, atomicMass: 140.12, category: "Lanthanide", info: "Used in catalytic converters and polishing powders." },
    { name: "Praseodymium", symbol: "Pr", number: 59, atomicMass: 140.91, category: "Lanthanide", info: "Used in strong magnets." },
    { name: "Neodymium", symbol: "Nd", number: 60, atomicMass: 144.24, category: "Lanthanide", info: "Used in headphones and powerful magnets." }
  );
  elements.push(
    { name: "Promethium", symbol: "Pm", number: 61, atomicMass: 145, category: "Lanthanide", info: "Radioactive, used in luminous paint." },
    { name: "Samarium", symbol: "Sm", number: 62, atomicMass: 150.36, category: "Lanthanide", info: "Used in magnets and nuclear reactors." },
    { name: "Europium", symbol: "Eu", number: 63, atomicMass: 151.96, category: "Lanthanide", info: "Used in TV screens and fluorescent lamps." },
    { name: "Gadolinium", symbol: "Gd", number: 64, atomicMass: 157.25, category: "Lanthanide", info: "Used in MRI contrast agents." },
    { name: "Terbium", symbol: "Tb", number: 65, atomicMass: 158.93, category: "Lanthanide", info: "Used in green phosphors in lighting." },
    { name: "Dysprosium", symbol: "Dy", number: 66, atomicMass: 162.50, category: "Lanthanide", info: "Used in high-performance magnets." },
    { name: "Holmium", symbol: "Ho", number: 67, atomicMass: 164.93, category: "Lanthanide", info: "Has the highest magnetic strength." },
    { name: "Erbium", symbol: "Er", number: 68, atomicMass: 167.26, category: "Lanthanide", info: "Used in fiber optics and lasers." },
    { name: "Thulium", symbol: "Tm", number: 69, atomicMass: 168.93, category: "Lanthanide", info: "Used in portable X-ray devices." },
    { name: "Ytterbium", symbol: "Yb", number: 70, atomicMass: 173.05, category: "Lanthanide", info: "Used in stress gauges and lasers." },
    { name: "Lutetium", symbol: "Lu", number: 71, atomicMass: 174.97, category: "Lanthanide", info: "Used in PET scan detectors." },
    { name: "Hafnium", symbol: "Hf", number: 72, atomicMass: 178.49, category: "Transition Metal", info: "Used in nuclear control rods." },
    { name: "Tantalum", symbol: "Ta", number: 73, atomicMass: 180.95, category: "Transition Metal", info: "Highly resistant to corrosion." },
    { name: "Tungsten", symbol: "W", number: 74, atomicMass: 183.84, category: "Transition Metal", info: "Has the highest melting point of any metal." },
    { name: "Rhenium", symbol: "Re", number: 75, atomicMass: 186.21, category: "Transition Metal", info: "Used in jet engines and thermocouples." },
    { name: "Osmium", symbol: "Os", number: 76, atomicMass: 190.23, category: "Transition Metal", info: "Densest naturally occurring element." },
    { name: "Iridium", symbol: "Ir", number: 77, atomicMass: 192.22, category: "Transition Metal", info: "Extremely corrosion-resistant." },
    { name: "Platinum", symbol: "Pt", number: 78, atomicMass: 195.08, category: "Transition Metal", info: "Precious metal used in jewelry and catalytic converters." },
    { name: "Gold", symbol: "Au", number: 79, atomicMass: 196.97, category: "Transition Metal", info: "Highly valued precious metal." },
    { name: "Mercury", symbol: "Hg", number: 80, atomicMass: 200.59, category: "Transition Metal", info: "Liquid at room temperature." },
    { name: "Thallium", symbol: "Tl", number: 81, atomicMass: 204.38, category: "Post-Transition Metal", info: "Highly toxic, used in electronics." },
    { name: "Lead", symbol: "Pb", number: 82, atomicMass: 207.2, category: "Post-Transition Metal", info: "Historically used in pipes and paints." },
    { name: "Bismuth", symbol: "Bi", number: 83, atomicMass: 208.98, category: "Post-Transition Metal", info: "Least toxic heavy metal, used in medicine." },
    { name: "Polonium", symbol: "Po", number: 84, atomicMass: 209, category: "Metalloid", info: "Highly radioactive." },
    { name: "Astatine", symbol: "At", number: 85, atomicMass: 210, category: "Halogen", info: "Rare and radioactive." },
    { name: "Radon", symbol: "Rn", number: 86, atomicMass: 222, category: "Noble Gas", info: "Radioactive gas found in soil." },
    { name: "Francium", symbol: "Fr", number: 87, atomicMass: 223, category: "Alkali Metal", info: "Extremely rare and radioactive." },
    { name: "Radium", symbol: "Ra", number: 88, atomicMass: 226, category: "Alkaline Earth Metal", info: "Formerly used in luminous paints." },
    { name: "Actinium", symbol: "Ac", number: 89, atomicMass: 227, category: "Actinide", info: "Radioactive element used in cancer treatment." },
    { name: "Thorium", symbol: "Th", number: 90, atomicMass: 232.04, category: "Actinide", info: "Potential fuel for nuclear reactors." }
  );
  elements.push(
    { name: "Protactinium", symbol: "Pa", number: 91, atomicMass: 231.04, category: "Actinide", info: "Radioactive, used in scientific research." },
    { name: "Uranium", symbol: "U", number: 92, atomicMass: 238.03, category: "Actinide", info: "Fuel for nuclear power plants." },
    { name: "Neptunium", symbol: "Np", number: 93, atomicMass: 237, category: "Actinide", info: "Byproduct of nuclear reactors." },
    { name: "Plutonium", symbol: "Pu", number: 94, atomicMass: 244, category: "Actinide", info: "Used in nuclear weapons and reactors." },
    { name: "Americium", symbol: "Am", number: 95, atomicMass: 243, category: "Actinide", info: "Used in smoke detectors." },
    { name: "Curium", symbol: "Cm", number: 96, atomicMass: 247, category: "Actinide", info: "Produced in nuclear reactors." },
    { name: "Berkelium", symbol: "Bk", number: 97, atomicMass: 247, category: "Actinide", info: "Synthesized in particle accelerators." },
    { name: "Californium", symbol: "Cf", number: 98, atomicMass: 251, category: "Actinide", info: "Used in neutron moisture gauges." },
    { name: "Einsteinium", symbol: "Es", number: 99, atomicMass: 252, category: "Actinide", info: "Named after Albert Einstein." },
    { name: "Fermium", symbol: "Fm", number: 100, atomicMass: 257, category: "Actinide", info: "Discovered in nuclear explosion debris." },
    { name: "Mendelevium", symbol: "Md", number: 101, atomicMass: 258, category: "Actinide", info: "Named after Dmitri Mendeleev." },
    { name: "Nobelium", symbol: "No", number: 102, atomicMass: 259, category: "Actinide", info: "Named after Alfred Nobel." },
    { name: "Lawrencium", symbol: "Lr", number: 103, atomicMass: 266, category: "Actinide", info: "Named after Ernest Lawrence." },
    { name: "Rutherfordium", symbol: "Rf", number: 104, atomicMass: 267, category: "Transition Metal", info: "Synthetic, short-lived element." },
    { name: "Dubnium", symbol: "Db", number: 105, atomicMass: 268, category: "Transition Metal", info: "Synthetic element with few uses." },
    { name: "Seaborgium", symbol: "Sg", number: 106, atomicMass: 269, category: "Transition Metal", info: "Named after Glenn T. Seaborg." },
    { name: "Bohrium", symbol: "Bh", number: 107, atomicMass: 270, category: "Transition Metal", info: "Highly radioactive and synthetic." },
    { name: "Hassium", symbol: "Hs", number: 108, atomicMass: 277, category: "Transition Metal", info: "Named after German state Hesse." },
    { name: "Meitnerium", symbol: "Mt", number: 109, atomicMass: 278, category: "Transition Metal", info: "Named after physicist Lise Meitner." },
    { name: "Darmstadtium", symbol: "Ds", number: 110, atomicMass: 281, category: "Transition Metal", info: "Discovered in Darmstadt, Germany." },
    { name: "Roentgenium", symbol: "Rg", number: 111, atomicMass: 282, category: "Transition Metal", info: "Named after Wilhelm Röntgen." },
    { name: "Copernicium", symbol: "Cn", number: 112, atomicMass: 285, category: "Transition Metal", info: "Named after Nicolaus Copernicus." },
    { name: "Nihonium", symbol: "Nh", number: 113, atomicMass: 286, category: "Post-Transition Metal", info: "Named after Japan (Nihon)." },
    { name: "Flerovium", symbol: "Fl", number: 114, atomicMass: 289, category: "Post-Transition Metal", info: "Named after the Flerov Laboratory." },
    { name: "Moscovium", symbol: "Mc", number: 115, atomicMass: 290, category: "Post-Transition Metal", info: "Named after Moscow region." },
    { name: "Livermorium", symbol: "Lv", number: 116, atomicMass: 293, category: "Post-Transition Metal", info: "Named after Lawrence Livermore Lab." },
    { name: "Tennessine", symbol: "Ts", number: 117, atomicMass: 294, category: "Halogen", info: "Named after Tennessee." },
    { name: "Oganesson", symbol: "Og", number: 118, atomicMass: 294, category: "Noble Gas", info: "Named after physicist Yuri Oganessian." }
  );
  const molecules = [
    { name: "Water", formula: "H₂O", molecularMass: 18.015 },
    { name: "Carbon Dioxide", formula: "CO₂", molecularMass: 44.01 },
    { name: "Sodium Chloride", formula: "NaCl", molecularMass: 58.44 },
    { name: "Glucose", formula: "C₆H₁₂O₆", molecularMass: 180.16 },
    { name: "Methane", formula: "CH₄", molecularMass: 16.04 },
    { name: "Ammonia", formula: "NH₃", molecularMass: 17.03 },
    { name: "Sulfuric Acid", formula: "H₂SO₄", molecularMass: 98.08 },
    { name: "Hydrochloric Acid", formula: "HCl", molecularMass: 36.46 },
    { name: "Acetic Acid", formula: "C₂H₄O₂", molecularMass: 60.05 },
    { name: "Ethanol", formula: "C₂H₅OH", molecularMass: 46.07 },
    { name: "Hydrogen Peroxide", formula: "H₂O₂", molecularMass: 34.01 },
    { name: "Nitric Acid", formula: "HNO₃", molecularMass: 63.01 },
    { name: "Calcium Carbonate", formula: "CaCO₃", molecularMass: 100.09 },
    { name: "Magnesium Sulfate", formula: "MgSO₄", molecularMass: 120.37 },
    { name: "Sodium Hydroxide", formula: "NaOH", molecularMass: 40.00 },
    { name: "Potassium Chloride", formula: "KCl", molecularMass: 74.55 },
    { name: "Calcium Sulfate", formula: "CaSO₄", molecularMass: 136.14 },
    { name: "Phosphoric Acid", formula: "H₃PO₄", molecularMass: 97.99 },
    { name: "Sodium Bicarbonate", formula: "NaHCO₃", molecularMass: 84.01 },
    { name: "Potassium Permanganate", formula: "KMnO₄", molecularMass: 158.04 },
    { name: "Copper(II) Sulfate", formula: "CuSO₄", molecularMass: 159.61 },
    { name: "Magnesium Carbonate", formula: "MgCO₃", molecularMass: 84.31 },
    { name: "Iron(III) Oxide", formula: "Fe₂O₃", molecularMass: 159.69 },
    { name: "Calcium Oxide", formula: "CaO", molecularMass: 56.08 },
    { name: "Aluminum Sulfate", formula: "Al₂(SO₄)₃", molecularMass: 342.15 },
    { name: "Sodium Nitrate", formula: "NaNO₃", molecularMass: 84.99 },
    { name: "Potassium Nitrate", formula: "KNO₃", molecularMass: 101.1 },
    { name: "Zinc Sulfate", formula: "ZnSO₄", molecularMass: 161.47 },
    { name: "Barium Chloride", formula: "BaCl₂", molecularMass: 137.33 },
    { name: "Ammonium Nitrate", formula: "NH₄NO₃", molecularMass: 80.04 },
    { name: "Copper(II) Carbonate", formula: "CuCO₃", molecularMass: 123.55 },
    { name: "Calcium Phosphate", formula: "Ca₃(PO₄)₂", molecularMass: 310.18 },
    { name: "Nitrous Oxide", formula: "N₂O", molecularMass: 44.01 },
    { name: "Sulfur Dioxide", formula: "SO₂", molecularMass: 64.06 },
    { name: "Chlorine", formula: "Cl₂", molecularMass: 70.90 },
    { name: "Acetone", formula: "C₃H₆O", molecularMass: 58.08 },
    { name: "Formaldehyde", formula: "CH₂O", molecularMass: 30.03 },
    { name: "Nitrogen Dioxide", formula: "NO₂", molecularMass: 46.00 },
    { name: "Phosphine", formula: "PH₃", molecularMass: 34.00 },
    { name: "Carbon Monoxide", formula: "CO", molecularMass: 28.01 },
    { name: "Hydrazine", formula: "N₂H₄", molecularMass: 32.05 },
    { name: "Chloroform", formula: "CHCl₃", molecularMass: 119.38 },
    { name: "Tetrachloromethane", formula: "CCl₄", molecularMass: 153.82 },
    { name: "Ozone", formula: "O₃", molecularMass: 48.00 },
    { name: "Uranium Hexafluoride", formula: "UF₆", molecularMass: 352.03 },
    { name: "Hydrogen Cyanide", formula: "HCN", molecularMass: 27.03 },
    { name: "Toluene", formula: "C₆H₅CH₃", molecularMass: 92.14 },
    { name: "Xylene", formula: "C₆H₄(CH₃)₂", molecularMass: 106.17 },
    { name: "Butane", formula: "C₄H₁₀", molecularMass: 58.12 },
    { name: "Octane", formula: "C₈H₁₈", molecularMass: 114.23 },
    { name: "Hexane", formula: "C₆H₁₄", molecularMass: 86.18 },
    { name: "Chlorobenzene", formula: "C₆H₅Cl", molecularMass: 112.56 },
    { name: "Styrene", formula: "C₆H₅CH=CH₂", molecularMass: 104.15 },
    { name: "Ethylene Glycol", formula: "C₂H₆O₂", molecularMass: 62.07 },
    { name: "Acetylene", formula: "C₂H₂", molecularMass: 26.04 },
    { name: "Isopropanol", formula: "C₃H₈O", molecularMass: 60.10 },
    { name: "Phenol", formula: "C₆H₆O", molecularMass: 94.11 },
    { name: "Methylamine", formula: "CH₃NH₂", molecularMass: 31.06 },
    { name: "Diethyl Ether", formula: "C₄H₁₀O", molecularMass: 74.12 },
    { name: "Acetaldehyde", formula: "C₂H₄O", molecularMass: 44.05 },
    { name: "Formic Acid", formula: "CH₂O₂", molecularMass: 46.03 },
    { name: "Sodium Chlorite", formula: "NaClO₂", molecularMass: 90.44 },
    { name: "Magnesium Hydroxide", formula: "Mg(OH)₂", molecularMass: 58.32 },
    { name: "Lithium Bromide", formula: "LiBr", molecularMass: 86.85 },
    { name: "Sodium Thiosulfate", formula: "Na₂S₂O₃", molecularMass: 158.11 },
    { name: "Potassium Iodide", formula: "KI", molecularMass: 166.00 },
    { name: "Bromine Water", formula: "Br₂ + H₂O", molecularMass: 160.91 },
    { name: "Chlorine Gas", formula: "Cl₂", molecularMass: 70.90 },
    { name: "Lactose", formula: "C₁₂H₂₂O₁₁", molecularMass: 342.30 },
    { name: "Fructose", formula: "C₆H₁₂O₆", molecularMass: 180.16 },
    { name: "Sucrose", formula: "C₁₂H₂₂O₁₁", molecularMass: 342.30 },
    { name: "Ascorbic Acid", formula: "C₆H₈O₆", molecularMass: 176.12 },
    { name: "Caffeine", formula: "C₈H₁₀N₄O₂", molecularMass: 194.19 },
    { name: "Nicotine", formula: "C₁₀H₁₄N₂", molecularMass: 162.23 },
    { name: "Linalool", formula: "C₆H₁₀O", molecularMass: 98.15 },
    { name: "Menthol", formula: "C₁₀H₁₈O", molecularMass: 156.27 },
    { name: "Aspirin", formula: "C₉H₈O₄", molecularMass: 180.16 },
    { name: "Ibuprofen", formula: "C₁₃H₁₈O₂", molecularMass: 206.29 },
    { name: "Acetaminophen", formula: "C₈H₉NO₂", molecularMass: 151.16 },
    { name: "Penicillin", formula: "C₁₆H₁₈N₂O₄S", molecularMass: 334.40 }
  ];
  